[programs.localnet]
sol_pay = "6qZM5m4H6ZspdKraMmJKCLNbFmw6hdWt6z3h71gScQmq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/sayantank/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
